plugins:
  enable_discourse_livestream:
    default: false
    client: true
  embeddable_chat_allowed_paths:
    type: list
    default: "/conference|/t"
    client: true
  topic_livestream_tag:
    default: "livestream"
    client: true
  conference_signup_registration_title:
    default: Registration
    client: true
  conference_signup_registration_description:
    textarea: true
    default: <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum.</p>
    client: true
  conference_registration_title:
    default: Complete Your Registration
    client: true
  conference_registration_description:
    textarea: true
    default: <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum.</p>
    client: true
  conference_registration_conf_selection_label:
    default: Which conference are you registering for?
    client: true
  conference_registration_company_label:
    default: What is your company?
    client: true
  conference_registration_title_label:
    default: What is your title?
    client: true
  conference_specific_title_label:
    default: Specify your title
    client: true
  conference_registration_country_label:
    default: What country are you in?
    client: true
  successful_conference_registration_come_back_label:
    default: Come back in
    client: true
  successful_conference_registration_thanks_message:
    default: Thanks for registering - Stay Tuned!
    client: true
  successful_conference_registration_message:
    textarea: true
    default: <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, amet animi autem beatae earum et harum laborum libero natus nemo neque officia perferendis porro possimus quam quia similique, ut voluptatum.</p>
    client: true
  conference_group_name:
    default: conf_2024_registered
    client: true
  conference_category_id:
    type: integer
    default: 18
    client: true
  available_conferences:
    type: list
    default: "live_april_9,Americas - Live,product-1,9am - 3:30pm CT,April 9th-12th,product-2,April 9th|semi_live_april_16,Europe / India - Semi-live,product-1,11am - 5:30pm CET / 4:30pm - 10:30pm IST,April 15th-18th,product-2,April 15th|semi_live_april_23,Asia-Pacific / Australia - Semi-live,product-1,11:00am - 5:30pm AEDT / 7:00am - 1:30pm HKT,April 23rd-26th,product-2,April 23rd"
    client: true
  conference_titles:
    type: list
    default: "developer:Developer|engineer:Engineer|architect:Architect|director:Director|vp:VP|cxo:CxO"
    client: true
  conference_agenda_meta_title:
    default: Agenda
    client: true
  conference_agenda_meta_description:
    default: Checkout the agenda of presentations and speakers for Conf!
    client: true
  conference_meta_title:
    default: Awesome Conf
    client: true
  conference_meta_description:
    default: Register for our annual conference for hands-on-keyboard problem solvers.
    client: true
  conference_start_time:
    default: "2024-04-09T06:00:00"
    client: true
  conference_start_timezone:
    default: "America/Chicago"
    client: true
  enable_livestream_chat:
    default: false
    client: true
  conference_chat_channel_ids:
    type: list
    default: ""
    client: true
  conf_channels_divider_index:
    default: 5
    client: true
  conference_enable_registration:
    default: true
    client: true
  conference_livestream_enabled_groups:
    type: group_list
    default: ""
    client: true
  agenda_endpoint_url:
    default: "https://286bhgrdwd.execute-api.us-east-1.amazonaws.com/Prod/agenda"
    client: true
  current_conf_stream_id:
    default: 1
    client: true
  speaker_title_user_field_id:
    default: "3"
    client: true
  stage_channel_link:
    type: list
    default: ""
    client: true
