plugins:
  discourse_livestream_enabled:
    default: false
    client: true
  embeddable_chat_allowed_paths:
    type: list
    default: "/t"
    client: true
  enable_modal_chat_on_mobile:
    default: true
    client: true
  livestream_chat_allowed_groups:
    default: "11" # default group trust_level_1
    client: true
    type: group_list


